import {
  ON_CELL_CLICK,
  ON_CHACKER_CLICK,
  CREATE_RND_POS,
  MOVE_BACK,
  FETCH_USER_DATA,
  SAVE_USER_DATA,
  DELETE_USER_DATA,
  LOAD_HISTORY_OF_MOVES,
} from "./action";

export {
  ON_CELL_CLICK,
  ON_CHACKER_CLICK,
  CREATE_RND_POS,
  MOVE_BACK,
  FETCH_USER_DATA,
  SAVE_USER_DATA,
  DELETE_USER_DATA,
  LOAD_HISTORY_OF_MOVES,
};
